import React from 'react';
import { Bot, Sparkles, Brain } from 'lucide-react';

export const AISummary = ({ summary }) => {
  if (!summary) {
    return (
      <div className="card" style={{ background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.15), rgba(59, 130, 246, 0.15))' }}>
        <div className="flex items-center gap-3 mb-3">
          <div className="p-2 rounded-xl bg-purple-500/20">
            <Brain size={24} className="text-purple-400" />
          </div>
          <h3 className="text-lg font-semibold text-white">Gemini AI Weather Intelligence</h3>
        </div>
        <p className="text-slate-300 leading-relaxed">
          AI summary currently unavailable. The WeatherAI API may be rate-limited or the Gemini service is temporarily offline.
        </p>
       
      </div>
    );
  }

  return (
    <div className="card" style={{ background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(59, 130, 246, 0.2))', borderColor: 'rgba(139, 92, 246, 0.3)' }}>
      <div className="flex items-center gap-3 mb-4">
        <div className="p-2 rounded-xl bg-gradient-to-br from-purple-500 to-blue-500">
          <Bot size={20} className="text-white" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-white">Gemini AI Analysis</h3>
          <p className="text-xs text-purple-300">AI-powered weather insights</p>
        </div>
        <Sparkles size={16} className="text-yellow-400 ml-auto" />
      </div>
      <p className="text-slate-200 leading-relaxed text-lg">{summary}</p>
      <div className="mt-4 pt-3 border-t border-white/10 text-right">
        <span className="text-xs text-slate-500">✨ Generated by Google Gemini AI</span>
      </div>
    </div>
  );
};